name: simple_biometric
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  app_settings: ^5.1.1
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  geolocator: ^11.0.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  json_annotation: ^4.8.1
  local_auth: ^2.1.8
  retrofit: ^4.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  dio:
  sqflite: ^2.3.2
  path: ^1.8.3
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  retrofit_generator:

flutter:
  uses-material-design: true
